title: Valentin Viennot
logo: /assets/img/valentin-viennot-min-sq.jpg
description: Software and Telecommunications Engineer by training, Inventor by nature
show_downloads: true
google_analytics: UA-167612032-1
theme: jekyll-theme-minimal
linkedin: https://www.linkedin.com/in/valentin-viennot
github: https://github.com/misterw97
email: mailto:valentin&#64;viennot.me